name: calendar-bot

channeld:
        - conda-forge

dependencies:
        - python-telegram-bot
        - pip:
                - google-api-python-client
                - google-auth-httplib2
                - google-auth-oauthlib

